CREATE TABLE [dbo].[VisitorInformation](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[IdNumber] [nvarchar](15) NOT NULL,
	[Dob] [nvarchar](15) NULL,
	[IdExpiry] [nvarchar](15) NULL,
	[IdType] [int] NOT NULL,
	[IdFrontSide] NVARCHAR(MAX) NOT NULL,
	[IdBackSide] NVARCHAR(MAX) NULL,
	[Photo] NVARCHAR(MAX) NULL,
	[Title] [nvarchar](15) NULL,
	[CompanyName] [nvarchar](50) NULL,
	[PurposeOfVisit] [nvarchar](50) NULL,
	[City] [nvarchar](25) NULL,
	[Address] [nvarchar](25) NULL,
	[Zip] [nvarchar](25) NULL,
	[State] [nvarchar](25) NULL,
	[CellPhone] [nvarchar](25) NULL,
	[Email] [nvarchar](25) NULL,
	[SocialSecurityNumber] [nvarchar](25) NULL,
	[HomePhoneNo] [nvarchar](25) NULL,
	[PassportNumber] [nvarchar](25) NULL,
	[PassportIssuePlace] [nvarchar](50) NULL,
	[PassportIssuedOn] [nvarchar](25) NULL,
	[PassportValidity] [nvarchar](25) NULL,
	[EmergencyContact] [nvarchar](25) NULL,
	[AliasName] [nvarchar](50) NULL,
	[Convicted] [bit] NULL,
	[Previous7YrResidency] [nvarchar](150) NULL,
	[PersonToBeVisited] [nvarchar](150) NULL,
	[AreaToBeVisited] [nvarchar](50) NULL,
	[VisitDate] [nvarchar](15) NULL,
	[VisitTime] [nvarchar](15) NULL,
	[DurationStart] [nvarchar](15) NULL,
	[DurationEnd] [nvarchar](15) NULL,
	[Duration] [nvarchar](15) NULL,
	[VisitFromDate] [nvarchar](15) NULL,
	[VisitToDuration] [nvarchar](15) NULL,
	[StartTime] [nvarchar](15) NULL,
	[EndTime] [nvarchar](15) NULL,
	[VisitDuration] [nvarchar](15) NULL,
	[DepartmentManager] [nvarchar](50) NULL,
	[ProductionManager] [nvarchar](50) NULL,
	[SecurityController] [nvarchar](50) NULL,
	[RFU1] [nvarchar](100) NULL,
	[RFU2] [nvarchar](100) NULL,
	[RFU3] [nvarchar](100) NULL,
	[RFU4] [nvarchar](100) NULL,
	[RFU5] [nvarchar](100) NULL,
	[RFU6] [nvarchar](100) NULL,
	[RFU7] [nvarchar](100) NULL,
	[RFU8] [nvarchar](100) NULL,
	[RFU9] [nvarchar](100) NULL,
	[RFU10] [nvarchar](100) NULL, 
    [CardNumber] [nvarchar](50) NULL, 
    [Status] NVARCHAR(50) NULL,
)
