using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GuestRegistrationDesktopUI.Library.TextProcessing
{
    public static class CountryCode
    {

    }

    public static class CountryAbbr
    {
        public static string getCountryFullName(string abbr)
        {
            Dictionary<string, string> countryAbbr = new Dictionary<string, string>();
            countryAbbr.Add("ABW", "ARUBA");
            countryAbbr.Add("AFG", "AFGHANISTAN");
            countryAbbr.Add("AGO", "ANGOLA");
            countryAbbr.Add("AIA", "ANGUILLA");
            countryAbbr.Add("ALA", "ÅLAND ISLANDS");
            countryAbbr.Add("ALB", "ALBANIA");
            countryAbbr.Add("AND", "ANDORRA");
            countryAbbr.Add("ARE", "UNITED ARAB EMIRATES");
            countryAbbr.Add("ARG", "ARGENTINA");
            countryAbbr.Add("ARM", "ARMENIA");
            countryAbbr.Add("ASM", "AMERICAN SAMOA");
            countryAbbr.Add("ATA", "ANTARCTICA");
            countryAbbr.Add("ATF", "FRENCH SOUTHERN TERRITORIES");
            countryAbbr.Add("ATG", "ANTIGUA AND BARBUDA");
            countryAbbr.Add("AUS", "AUSTRALIA");
            countryAbbr.Add("AUT", "AUSTRIA");
            countryAbbr.Add("AZE", "AZERBAIJAN");
            countryAbbr.Add("BDI", "BURUNDI");
            countryAbbr.Add("BEL", "BELGIUM");
            countryAbbr.Add("BEN", "BENIN");
            countryAbbr.Add("BES", "BONAIRE, SINT EUSTATIUS AND SABA");
            countryAbbr.Add("BFA", "BURKINA FASO");
            countryAbbr.Add("BGD", "BANGLADESH");
            countryAbbr.Add("BGR", "BULGARIA");
            countryAbbr.Add("BHR", "BAHRAIN");
            countryAbbr.Add("BHS", "BAHAMAS");
            countryAbbr.Add("BIH", "BOSNIA AND HERZEGOVINA");
            countryAbbr.Add("BLM", "SAINT BARTHÉLEMY");
            countryAbbr.Add("BLR", "BELARUS");
            countryAbbr.Add("BLZ", "BELIZE");
            countryAbbr.Add("BMU", "BERMUDA");
            countryAbbr.Add("BOL", "BOLIVIA ");
            countryAbbr.Add("BRA", "BRAZIL");
            countryAbbr.Add("BRB", "BARBADOS");
            countryAbbr.Add("BRN", "BRUNEI DARUSSALAM");
            countryAbbr.Add("BTN", "BHUTAN");
            countryAbbr.Add("BVT", "BOUVET ISLAND");
            countryAbbr.Add("BWA", "BOTSWANA");
            countryAbbr.Add("CAF", "CENTRAL AFRICAN REPUBLIC");
            countryAbbr.Add("CAN", "CANADA");
            countryAbbr.Add("CCK", "COCOS ISLANDS");
            countryAbbr.Add("CHE", "SWITZERLAND");
            countryAbbr.Add("CHL", "CHILE");
            countryAbbr.Add("CHN", "CHINA");
            countryAbbr.Add("CIV", "CÔTE D'IVOIRE");
            countryAbbr.Add("CMR", "CAMEROON");
            countryAbbr.Add("COD", "CONGO, DEMOCRATIC REPUBLIC OF THE");
            countryAbbr.Add("COG", "CONGO");
            countryAbbr.Add("COK", "COOK ISLANDS");
            countryAbbr.Add("COL", "COLOMBIA");
            countryAbbr.Add("COM", "COMOROS");
            countryAbbr.Add("CPV", "CABO VERDE");
            countryAbbr.Add("CRI", "COSTA RICA");
            countryAbbr.Add("CUB", "CUBA");
            countryAbbr.Add("CUW", "CURAÇAO");
            countryAbbr.Add("CXR", "CHRISTMAS ISLAND");
            countryAbbr.Add("CYM", "CAYMAN ISLANDS");
            countryAbbr.Add("CYP", "CYPRUS");
            countryAbbr.Add("CZE", "CZECHIA");
            countryAbbr.Add("DEU", "GERMANY");
            countryAbbr.Add("DJI", "DJIBOUTI");
            countryAbbr.Add("DMA", "DOMINICA");
            countryAbbr.Add("DNK", "DENMARK");
            countryAbbr.Add("DOM", "DOMINICAN REPUBLIC");
            countryAbbr.Add("DZA", "ALGERIA");
            countryAbbr.Add("ECU", "ECUADOR");
            countryAbbr.Add("EGY", "EGYPT");
            countryAbbr.Add("ERI", "ERITREA");
            countryAbbr.Add("ESH", "WESTERN SAHARA");
            countryAbbr.Add("ESP", "SPAIN");
            countryAbbr.Add("EST", "ESTONIA");
            countryAbbr.Add("ETH", "ETHIOPIA");
            countryAbbr.Add("FIN", "FINLAND");
            countryAbbr.Add("FJI", "FIJI");
            countryAbbr.Add("FLK", "FALKLAND ISLANDS (MALVINAS)");
            countryAbbr.Add("FRA", "FRANCE");
            countryAbbr.Add("FRO", "FAROE ISLANDS");
            countryAbbr.Add("FSM", "MICRONESIA (FEDERATED STATES OF)");
            countryAbbr.Add("GAB", "GABON");
            countryAbbr.Add("GBR", "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRE");
            countryAbbr.Add("GEO", "GEORGIA");
            countryAbbr.Add("GGY", "GUERNSEY");
            countryAbbr.Add("GHA", "GHANA");
            countryAbbr.Add("GIB", "GIBRALTAR");
            countryAbbr.Add("GIN", "GUINEA");
            countryAbbr.Add("GLP", "GUADELOUPE");
            countryAbbr.Add("GMB", "GAMBIA");
            countryAbbr.Add("GNB", "GUINEA-BISSAU");
            countryAbbr.Add("GNQ", "EQUATORIAL GUINEA");
            countryAbbr.Add("GRC", "GREECE");
            countryAbbr.Add("GRD", "GRENADA");
            countryAbbr.Add("GRL", "GREENLAND");
            countryAbbr.Add("GTM", "GUATEMALA");
            countryAbbr.Add("GUF", "FRENCH GUIANA");
            countryAbbr.Add("GUM", "GUAM");
            countryAbbr.Add("GUY", "GUYANA");
            countryAbbr.Add("HKG", "HONG KONG");
            countryAbbr.Add("HMD", "HEARD ISLAND AND MCDONALD ISLANDS");
            countryAbbr.Add("HND", "HONDURAS");
            countryAbbr.Add("HRV", "CROATIA");
            countryAbbr.Add("HTI", "HAITI");
            countryAbbr.Add("HUN", "HUNGARY");
            countryAbbr.Add("IDN", "INDONESIA");
            countryAbbr.Add("IMN", "ISLE OF MAN");
            countryAbbr.Add("IND", "INDIA");
            countryAbbr.Add("IOT", "BRITISH INDIAN OCEAN TERRITORY");
            countryAbbr.Add("IRL", "IRELAND");
            countryAbbr.Add("IRN", "IRAN (ISLAMIC REPUBLIC OF)");
            countryAbbr.Add("IRQ", "IRAQ");
            countryAbbr.Add("ISL", "ICELAND");
            countryAbbr.Add("ISR", "ISRAEL");
            countryAbbr.Add("ITA", "ITALY");
            countryAbbr.Add("JAM", "JAMAICA");
            countryAbbr.Add("JEY", "JERSEY");
            countryAbbr.Add("JOR", "JORDAN");
            countryAbbr.Add("JPN", "JAPAN");
            countryAbbr.Add("KAZ", "KAZAKHSTAN");
            countryAbbr.Add("KEN", "KENYA");
            countryAbbr.Add("KGZ", "KYRGYZSTAN");
            countryAbbr.Add("KHM", "CAMBODIA");
            countryAbbr.Add("KIR", "KIRIBATI");
            countryAbbr.Add("KNA", "SAINT KITTS AND NEVIS");
            countryAbbr.Add("KOR", "KOREA, REPUBLIC OF");
            countryAbbr.Add("KWT", "KUWAIT");
            countryAbbr.Add("LAO", "LAO PEOPLE'S DEMOCRATIC REPUBLIC");
            countryAbbr.Add("LBN", "LEBANON");
            countryAbbr.Add("LBR", "LIBERIA");
            countryAbbr.Add("LBY", "LIBYA");
            countryAbbr.Add("LCA", "SAINT LUCIA");
            countryAbbr.Add("LIE", "LIECHTENSTEIN");
            countryAbbr.Add("LKA", "SRI LANKA");
            countryAbbr.Add("LSO", "LESOTHO");
            countryAbbr.Add("LTU", "LITHUANIA");
            countryAbbr.Add("LUX", "LUXEMBOURG");
            countryAbbr.Add("LVA", "LATVIA");
            countryAbbr.Add("MAC", "MACAO");
            countryAbbr.Add("MAF", "SAINT MARTIN (FRENCH PART)");
            countryAbbr.Add("MAR", "MOROCCO");
            countryAbbr.Add("MCO", "MONACO");
            countryAbbr.Add("MDA", "MOLDOVA, REPUBLIC OF");
            countryAbbr.Add("MDG", "MADAGASCAR");
            countryAbbr.Add("MDV", "MALDIVES");
            countryAbbr.Add("MEX", "MEXICO");
            countryAbbr.Add("MHL", "MARSHALL ISLANDS");
            countryAbbr.Add("MKD", "NORTH MACEDONIA");
            countryAbbr.Add("MLI", "MALI");
            countryAbbr.Add("MLT", "MALTA");
            countryAbbr.Add("MMR", "MYANMAR");
            countryAbbr.Add("MNE", "MONTENEGRO");
            countryAbbr.Add("MNG", "MONGOLIA");
            countryAbbr.Add("MNP", "NORTHERN MARIANA ISLANDS");
            countryAbbr.Add("MOZ", "MOZAMBIQUE");
            countryAbbr.Add("MRT", "MAURITANIA");
            countryAbbr.Add("MSR", "MONTSERRAT");
            countryAbbr.Add("MTQ", "MARTINIQUE");
            countryAbbr.Add("MUS", "MAURITIUS");
            countryAbbr.Add("MWI", "MALAWI");
            countryAbbr.Add("MYS", "MALAYSIA");
            countryAbbr.Add("MYT", "MAYOTTE");
            countryAbbr.Add("NAM", "NAMIBIA");
            countryAbbr.Add("NCL", "NEW CALEDONIA");
            countryAbbr.Add("NER", "NIGER");
            countryAbbr.Add("NFK", "NORFOLK ISLAND");
            countryAbbr.Add("NGA", "NIGERIA");
            countryAbbr.Add("NIC", "NICARAGUA");
            countryAbbr.Add("NIU", "NIUE");
            countryAbbr.Add("NLD", "NETHERLANDS, KINGDOM OF THE");
            countryAbbr.Add("NOR", "NORWAY");
            countryAbbr.Add("NPL", "NEPAL");
            countryAbbr.Add("NRU", "NAURU");
            countryAbbr.Add("NZL", "NEW ZEALAND");
            countryAbbr.Add("OMN", "OMAN");
            countryAbbr.Add("PAK", "PAKISTAN");
            countryAbbr.Add("PAN", "PANAMA");
            countryAbbr.Add("PCN", "PITCAIRN");
            countryAbbr.Add("PER", "PERU");
            countryAbbr.Add("PHL", "PHILIPPINES");
            countryAbbr.Add("PLW", "PALAU");
            countryAbbr.Add("PNG", "PAPUA NEW GUINEA");
            countryAbbr.Add("POL", "POLAND");
            countryAbbr.Add("PRI", "PUERTO RICO");
            countryAbbr.Add("PRK", "KOREA (DEMOCRATIC PEOPLE'S REPUBLIC OF)");
            countryAbbr.Add("PRT", "PORTUGAL");
            countryAbbr.Add("PRY", "PARAGUAY");
            countryAbbr.Add("PSE", "PALESTINE, STATE OF");
            countryAbbr.Add("PYF", "FRENCH POLYNESIA");
            countryAbbr.Add("QAT", "QATAR");
            countryAbbr.Add("REU", "RÉUNION");
            countryAbbr.Add("ROU", "ROMANIA");
            countryAbbr.Add("RUS", "RUSSIAN FEDERATION");
            countryAbbr.Add("RWA", "RWANDA");
            countryAbbr.Add("SAU", "SAUDI ARABIA");
            countryAbbr.Add("SDN", "SUDAN");
            countryAbbr.Add("SEN", "SENEGAL");
            countryAbbr.Add("SGP", "SINGAPORE");
            countryAbbr.Add("SGS", "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS");
            countryAbbr.Add("SHN", "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA");
            countryAbbr.Add("SJM", "SVALBARD AND JAN MAYEN");
            countryAbbr.Add("SLB", "SOLOMON ISLANDS");
            countryAbbr.Add("SLE", "SIERRA LEONE");
            countryAbbr.Add("SLV", "EL SALVADOR");
            countryAbbr.Add("SMR", "SAN MARINO");
            countryAbbr.Add("SOM", "SOMALIA");
            countryAbbr.Add("SPM", "SAINT PIERRE AND MIQUELON");
            countryAbbr.Add("SRB", "SERBIA");
            countryAbbr.Add("SSD", "SOUTH SUDAN");
            countryAbbr.Add("STP", "SAO TOME AND PRINCIPE");
            countryAbbr.Add("SUR", "SURINAME");
            countryAbbr.Add("SVK", "SLOVAKIA");
            countryAbbr.Add("SVN", "SLOVENIA");
            countryAbbr.Add("SWE", "SWEDEN");
            countryAbbr.Add("SWZ", "ESWATINI");
            countryAbbr.Add("SXM", "SINT MAARTEN (DUTCH PART)");
            countryAbbr.Add("SYC", "SEYCHELLES");
            countryAbbr.Add("SYR", "SYRIAN ARAB REPUBLIC");
            countryAbbr.Add("TCA", "TURKS AND CAICOS ISLANDS");
            countryAbbr.Add("TCD", "CHAD");
            countryAbbr.Add("TGO", "TOGO");
            countryAbbr.Add("THA", "THAILAND");
            countryAbbr.Add("TJK", "TAJIKISTAN");
            countryAbbr.Add("TKL", "TOKELAU");
            countryAbbr.Add("TKM", "TURKMENISTAN");
            countryAbbr.Add("TLS", "TIMOR-LESTE");
            countryAbbr.Add("TON", "TONGA");
            countryAbbr.Add("TTO", "TRINIDAD AND TOBAGO");
            countryAbbr.Add("TUN", "TUNISIA");
            countryAbbr.Add("TUR", "TÜRKIYE");
            countryAbbr.Add("TUV", "TUVALU");
            countryAbbr.Add("TWN", "TAIWAN, PROVINCE OF CHINA");
            countryAbbr.Add("TZA", "TANZANIA, UNITED REPUBLIC OF");
            countryAbbr.Add("UGA", "UGANDA");
            countryAbbr.Add("UKR", "UKRAINE");
            countryAbbr.Add("UMI", "UNITED STATES MINOR OUTLYING ISLANDS");
            countryAbbr.Add("URY", "URUGUAY");
            countryAbbr.Add("USA", "UNITED STATES OF AMERICA");
            countryAbbr.Add("UZB", "UZBEKISTAN");
            countryAbbr.Add("VAT", "HOLY SEE");
            countryAbbr.Add("VCT", "SAINT VINCENT AND THE GRENADINES");
            countryAbbr.Add("VEN", "VENEZUELA (BOLIVARIAN REPUBLIC OF)");
            countryAbbr.Add("VGB", "VIRGIN ISLANDS (BRITISH)");
            countryAbbr.Add("VIR", "VIRGIN ISLANDS (U.S.)");
            countryAbbr.Add("VNM", "VIET NAM");
            countryAbbr.Add("VUT", "VANUATU");
            countryAbbr.Add("WLF", "WALLIS AND FUTUNA");
            countryAbbr.Add("WSM", "SAMOA");
            countryAbbr.Add("YEM", "YEMEN");
            countryAbbr.Add("ZAF", "SOUTH AFRICA");
            countryAbbr.Add("ZMB", "ZAMBIA");
            countryAbbr.Add("ZWE", "ZIMBABWE");


            if (countryAbbr.ContainsKey(abbr))
            {
                return countryAbbr[abbr];
            }
            else
            {
                return abbr;
            }
            return countryAbbr[abbr];
        }

    }
}
