using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GuestRegistrationDesktopUI.Library.TextProcessing
{
    public static class CountryCode
    {

    }

    public static class CountryAbbr
    {
        public static string getCountryFullName(string abbr)
        {
            Dictionary<string, string> countryAbbr = new Dictionary<string, string>();
            countryAbbr.Add("ABW", "Aruba");
            countryAbbr.Add("AFG", "Afghanistan");
            countryAbbr.Add("AGO", "Angola");
            countryAbbr.Add("AIA", "Anguilla");
            countryAbbr.Add("ALA", "Åland Islands");
            countryAbbr.Add("ALB", "Albania");
            countryAbbr.Add("AND", "Andorra");
            countryAbbr.Add("ARE", "United Arab Emirates");
            countryAbbr.Add("ARG", "Argentina");
            countryAbbr.Add("ARM", "Armenia");
            countryAbbr.Add("ASM", "American Samoa");
            countryAbbr.Add("ATA", "Antarctica");
            countryAbbr.Add("ATF", "French Southern Territories");
            countryAbbr.Add("ATG", "Antigua and Barbuda");
            countryAbbr.Add("AUS", "Australia");
            countryAbbr.Add("AUT", "Austria");
            countryAbbr.Add("AZE", "Azerbaijan");
            countryAbbr.Add("BDI", "Burundi");
            countryAbbr.Add("BEL", "Belgium");
            countryAbbr.Add("BEN", "Benin");
            countryAbbr.Add("BES", "Bonaire, Sint Eustatius and Saba");
            countryAbbr.Add("BFA", "Burkina Faso");
            countryAbbr.Add("BGD", "Bangladesh");
            countryAbbr.Add("BGR", "Bulgaria");
            countryAbbr.Add("BHR", "Bahrain");
            countryAbbr.Add("BHS", "Bahamas");
            countryAbbr.Add("BIH", "Bosnia and Herzegovina");
            countryAbbr.Add("BLM", "Saint Barthélemy");
            countryAbbr.Add("BLR", "Belarus");
            countryAbbr.Add("BLZ", "Belize");
            countryAbbr.Add("BMU", "Bermuda");
            countryAbbr.Add("BOL", "Bolivia (Plurinational State of)");
            countryAbbr.Add("BRA", "Brazil");
            countryAbbr.Add("BRB", "Barbados");
            countryAbbr.Add("BRN", "Brunei Darussalam");
            countryAbbr.Add("BTN", "Bhutan");
            countryAbbr.Add("BVT", "Bouvet Island");
            countryAbbr.Add("BWA", "Botswana");
            countryAbbr.Add("CAF", "Central African Republic");
            countryAbbr.Add("CAN", "Canada");
            countryAbbr.Add("CCK", "Cocos (Keeling) Islands");
            countryAbbr.Add("CHE", "Switzerland");
            countryAbbr.Add("CHL", "Chile");
            countryAbbr.Add("CHN", "China");
            countryAbbr.Add("CIV", "Côte d'Ivoire");
            countryAbbr.Add("CMR", "Cameroon");
            countryAbbr.Add("COD", "Congo, Democratic Republic of the");
            countryAbbr.Add("COG", "Congo");
            countryAbbr.Add("COK", "Cook Islands");
            countryAbbr.Add("COL", "Colombia");
            countryAbbr.Add("COM", "Comoros");
            countryAbbr.Add("CPV", "Cabo Verde");
            countryAbbr.Add("CRI", "Costa Rica");
            countryAbbr.Add("CUB", "Cuba");
            countryAbbr.Add("CUW", "Curaçao");
            countryAbbr.Add("CXR", "Christmas Island");
            countryAbbr.Add("CYM", "Cayman Islands");
            countryAbbr.Add("CYP", "Cyprus");
            countryAbbr.Add("CZE", "Czechia");
            countryAbbr.Add("DEU", "Germany");
            countryAbbr.Add("DJI", "Djibouti");
            countryAbbr.Add("DMA", "Dominica");
            countryAbbr.Add("DNK", "Denmark");
            countryAbbr.Add("DOM", "Dominican Republic");
            countryAbbr.Add("DZA", "Algeria");
            countryAbbr.Add("ECU", "Ecuador");
            countryAbbr.Add("EGY", "Egypt");
            countryAbbr.Add("ERI", "Eritrea");
            countryAbbr.Add("ESH", "Western Sahara");
            countryAbbr.Add("ESP", "Spain");
            countryAbbr.Add("EST", "Estonia");
            countryAbbr.Add("ETH", "Ethiopia");
            countryAbbr.Add("FIN", "Finland");
            countryAbbr.Add("FJI", "Fiji");
            countryAbbr.Add("FLK", "Falkland Islands (Malvinas)");
            countryAbbr.Add("FRA", "France");
            countryAbbr.Add("FRO", "Faroe Islands");
            countryAbbr.Add("FSM", "Micronesia (Federated States of)");
            countryAbbr.Add("GAB", "Gabon");
            countryAbbr.Add("GBR", "United Kingdom of Great Britain and Northern Ire");
            countryAbbr.Add("GEO", "Georgia");
            countryAbbr.Add("GGY", "Guernsey");
            countryAbbr.Add("GHA", "Ghana");
            countryAbbr.Add("GIB", "Gibraltar");
            countryAbbr.Add("GIN", "Guinea");
            countryAbbr.Add("GLP", "Guadeloupe");
            countryAbbr.Add("GMB", "Gambia");
            countryAbbr.Add("GNB", "Guinea-Bissau");
            countryAbbr.Add("GNQ", "Equatorial Guinea");
            countryAbbr.Add("GRC", "Greece");
            countryAbbr.Add("GRD", "Grenada");
            countryAbbr.Add("GRL", "Greenland");
            countryAbbr.Add("GTM", "Guatemala");
            countryAbbr.Add("GUF", "French Guiana");
            countryAbbr.Add("GUM", "Guam");
            countryAbbr.Add("GUY", "Guyana");
            countryAbbr.Add("HKG", "Hong Kong");
            countryAbbr.Add("HMD", "Heard Island and McDonald Islands");
            countryAbbr.Add("HND", "Honduras");
            countryAbbr.Add("HRV", "Croatia");
            countryAbbr.Add("HTI", "Haiti");
            countryAbbr.Add("HUN", "Hungary");
            countryAbbr.Add("IDN", "Indonesia");
            countryAbbr.Add("IMN", "Isle of Man");
            countryAbbr.Add("IND", "India");
            countryAbbr.Add("IOT", "British Indian Ocean Territory");
            countryAbbr.Add("IRL", "Ireland");
            countryAbbr.Add("IRN", "Iran (Islamic Republic of)");
            countryAbbr.Add("IRQ", "Iraq");
            countryAbbr.Add("ISL", "Iceland");
            countryAbbr.Add("ISR", "Israel");
            countryAbbr.Add("ITA", "Italy");
            countryAbbr.Add("JAM", "Jamaica");
            countryAbbr.Add("JEY", "Jersey");
            countryAbbr.Add("JOR", "Jordan");
            countryAbbr.Add("JPN", "Japan");
            countryAbbr.Add("KAZ", "Kazakhstan");
            countryAbbr.Add("KEN", "Kenya");
            countryAbbr.Add("KGZ", "Kyrgyzstan");
            countryAbbr.Add("KHM", "Cambodia");
            countryAbbr.Add("KIR", "Kiribati");
            countryAbbr.Add("KNA", "Saint Kitts and Nevis");
            countryAbbr.Add("KOR", "Korea, Republic of");
            countryAbbr.Add("KWT", "Kuwait");
            countryAbbr.Add("LAO", "Lao People's Democratic Republic");
            countryAbbr.Add("LBN", "Lebanon");
            countryAbbr.Add("LBR", "Liberia");
            countryAbbr.Add("LBY", "Libya");
            countryAbbr.Add("LCA", "Saint Lucia");
            countryAbbr.Add("LIE", "Liechtenstein");
            countryAbbr.Add("LKA", "Sri Lanka");
            countryAbbr.Add("LSO", "Lesotho");
            countryAbbr.Add("LTU", "Lithuania");
            countryAbbr.Add("LUX", "Luxembourg");
            countryAbbr.Add("LVA", "Latvia");
            countryAbbr.Add("MAC", "Macao");
            countryAbbr.Add("MAF", "Saint Martin (French part)");
            countryAbbr.Add("MAR", "Morocco");
            countryAbbr.Add("MCO", "Monaco");
            countryAbbr.Add("MDA", "Moldova, Republic of");
            countryAbbr.Add("MDG", "Madagascar");
            countryAbbr.Add("MDV", "Maldives");
            countryAbbr.Add("MEX", "Mexico");
            countryAbbr.Add("MHL", "Marshall Islands");
            countryAbbr.Add("MKD", "North Macedonia");
            countryAbbr.Add("MLI", "Mali");
            countryAbbr.Add("MLT", "Malta");
            countryAbbr.Add("MMR", "Myanmar");
            countryAbbr.Add("MNE", "Montenegro");
            countryAbbr.Add("MNG", "Mongolia");
            countryAbbr.Add("MNP", "Northern Mariana Islands");
            countryAbbr.Add("MOZ", "Mozambique");
            countryAbbr.Add("MRT", "Mauritania");
            countryAbbr.Add("MSR", "Montserrat");
            countryAbbr.Add("MTQ", "Martinique");
            countryAbbr.Add("MUS", "Mauritius");
            countryAbbr.Add("MWI", "Malawi");
            countryAbbr.Add("MYS", "Malaysia");
            countryAbbr.Add("MYT", "Mayotte");
            countryAbbr.Add("NAM", "Namibia");
            countryAbbr.Add("NCL", "New Caledonia");
            countryAbbr.Add("NER", "Niger");
            countryAbbr.Add("NFK", "Norfolk Island");
            countryAbbr.Add("NGA", "Nigeria");
            countryAbbr.Add("NIC", "Nicaragua");
            countryAbbr.Add("NIU", "Niue");
            countryAbbr.Add("NLD", "Netherlands, Kingdom of the");
            countryAbbr.Add("NOR", "Norway");
            countryAbbr.Add("NPL", "Nepal");
            countryAbbr.Add("NRU", "Nauru");
            countryAbbr.Add("NZL", "New Zealand");
            countryAbbr.Add("OMN", "Oman");
            countryAbbr.Add("PAK", "Pakistan");
            countryAbbr.Add("PAN", "Panama");
            countryAbbr.Add("PCN", "Pitcairn");
            countryAbbr.Add("PER", "Peru");
            countryAbbr.Add("PHL", "Philippines");
            countryAbbr.Add("PLW", "Palau");
            countryAbbr.Add("PNG", "Papua New Guinea");
            countryAbbr.Add("POL", "Poland");
            countryAbbr.Add("PRI", "Puerto Rico");
            countryAbbr.Add("PRK", "Korea (Democratic People's Republic of)");
            countryAbbr.Add("PRT", "Portugal");
            countryAbbr.Add("PRY", "Paraguay");
            countryAbbr.Add("PSE", "Palestine, State of");
            countryAbbr.Add("PYF", "French Polynesia");
            countryAbbr.Add("QAT", "Qatar");
            countryAbbr.Add("REU", "Réunion");
            countryAbbr.Add("ROU", "Romania");
            countryAbbr.Add("RUS", "Russian Federation");
            countryAbbr.Add("RWA", "Rwanda");
            countryAbbr.Add("SAU", "Saudi Arabia");
            countryAbbr.Add("SDN", "Sudan");
            countryAbbr.Add("SEN", "Senegal");
            countryAbbr.Add("SGP", "Singapore");
            countryAbbr.Add("SGS", "South Georgia and the South Sandwich Islands");
            countryAbbr.Add("SHN", "Saint Helena, Ascension and Tristan da Cunha");
            countryAbbr.Add("SJM", "Svalbard and Jan Mayen");
            countryAbbr.Add("SLB", "Solomon Islands");
            countryAbbr.Add("SLE", "Sierra Leone");
            countryAbbr.Add("SLV", "El Salvador");
            countryAbbr.Add("SMR", "San Marino");
            countryAbbr.Add("SOM", "Somalia");
            countryAbbr.Add("SPM", "Saint Pierre and Miquelon");
            countryAbbr.Add("SRB", "Serbia");
            countryAbbr.Add("SSD", "South Sudan");
            countryAbbr.Add("STP", "Sao Tome and Principe");
            countryAbbr.Add("SUR", "Suriname");
            countryAbbr.Add("SVK", "Slovakia");
            countryAbbr.Add("SVN", "Slovenia");
            countryAbbr.Add("SWE", "Sweden");
            countryAbbr.Add("SWZ", "Eswatini");
            countryAbbr.Add("SXM", "Sint Maarten (Dutch part)");
            countryAbbr.Add("SYC", "Seychelles");
            countryAbbr.Add("SYR", "Syrian Arab Republic");
            countryAbbr.Add("TCA", "Turks and Caicos Islands");
            countryAbbr.Add("TCD", "Chad");
            countryAbbr.Add("TGO", "Togo");
            countryAbbr.Add("THA", "Thailand");
            countryAbbr.Add("TJK", "Tajikistan");
            countryAbbr.Add("TKL", "Tokelau");
            countryAbbr.Add("TKM", "Turkmenistan");
            countryAbbr.Add("TLS", "Timor-Leste");
            countryAbbr.Add("TON", "Tonga");
            countryAbbr.Add("TTO", "Trinidad and Tobago");
            countryAbbr.Add("TUN", "Tunisia");
            countryAbbr.Add("TUR", "Türkiye");
            countryAbbr.Add("TUV", "Tuvalu");
            countryAbbr.Add("TWN", "Taiwan, Province of China");
            countryAbbr.Add("TZA", "Tanzania, United Republic of");
            countryAbbr.Add("UGA", "Uganda");
            countryAbbr.Add("UKR", "Ukraine");
            countryAbbr.Add("UMI", "United States Minor Outlying Islands");
            countryAbbr.Add("URY", "Uruguay");
            countryAbbr.Add("USA", "United States of America");
            countryAbbr.Add("UZB", "Uzbekistan");
            countryAbbr.Add("VAT", "Holy See");
            countryAbbr.Add("VCT", "Saint Vincent and the Grenadines");
            countryAbbr.Add("VEN", "Venezuela (Bolivarian Republic of)");
            countryAbbr.Add("VGB", "Virgin Islands (British)");
            countryAbbr.Add("VIR", "Virgin Islands (U.S.)");
            countryAbbr.Add("VNM", "Viet Nam");
            countryAbbr.Add("VUT", "Vanuatu");
            countryAbbr.Add("WLF", "Wallis and Futuna");
            countryAbbr.Add("WSM", "Samoa");
            countryAbbr.Add("YEM", "Yemen");
            countryAbbr.Add("ZAF", "South Africa");
            countryAbbr.Add("ZMB", "Zambia");
            countryAbbr.Add("ZWE", "Zimbabwe");
            return countryAbbr[abbr];
        }

    }
}
